<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="Moq" Version="4.20.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Coditech.Engine.DBTM\Coditech.Engine.DBTM.csproj" />
    <ProjectReference Include="..\Coditech.API.Data.Custom\Coditech.API.Data.Custom.csproj" />
    <ProjectReference Include="..\Coditech.API.Model.Custom\Coditech.API.Model.Custom.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Coditech.API.Data">
      <HintPath>..\SharedLibraries\Coditech.API.Data.dll</HintPath>
    </Reference>
    <Reference Include="Coditech.Common.API">
      <HintPath>..\SharedLibraries\Coditech.Common.API.dll</HintPath>
    </Reference>
    <Reference Include="Coditech.Common.API.Model">
      <HintPath>..\SharedLibraries\Coditech.Common.API.Model.dll</HintPath>
    </Reference>
    <Reference Include="Coditech.Common.Helper">
      <HintPath>..\SharedLibraries\Coditech.Common.Helper.dll</HintPath>
    </Reference>
    <Reference Include="Coditech.Common.Logger">
      <HintPath>..\SharedLibraries\Coditech.Common.Logger.dll</HintPath>
    </Reference>
    <Reference Include="Coditech.Common.Service">
      <HintPath>..\SharedLibraries\Coditech.Common.Service.dll</HintPath>
    </Reference>
    <Reference Include="Coditech.Resources">
      <HintPath>..\SharedLibraries\Coditech.Resources.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
